Update IAB Workshop.md
ietf-wg-nmop/Logistic pull request #9
Opened 2024-06-04 10:40 UTC by billwuqin

Add a few Editorial changes, in addition I think we should
1. Encourage collaboration with other venues such as MEF, TMF Multi-SDO initiative, ONUG for collaboration
2. Endorse the first layering model deployment guidline described in RFC8969.
3. Ambitious word is a little bit aggresive, can we replace with incentive?
4. We need to also consider PoC in some industry initiative such as ETSI ZSM, TMF catalyst project,  EANTC multi-vendor interoperability test event

2024-06-05 01:27 UTC, mjethanandani reviewed
Hi Qin, I feel the current description is in good shape and does not need further tweaks to take it to the IAB. Further edits can be had once IAB has had a chance to review the current description.

2024-06-06 02:32 UTC, billwuqin commented
OK, I can hold my comments until it gets discussed in IAB.

2024-06-18 00:57 UTC, billwuqin commented
Comparing NANOG, RIPE, APNIC, Autocon, I think TMF, MEF, ETSI ZSM don't represent pure operator community, may be not nessesary to be listed. So I tweak the proposal.

2024-06-18 08:11 UTC, boucadair requested changes
Thanks. Some proposed edits.

2024-06-18 08:11 UTC, boucadair commented on IAB Workshop.md
> +- Data consistency to support richer full stack observability (Data & Knowledge)
```suggestion
- Data consistency to support richer observability (Data & Knowledge)
```

Not sure "full stack" will understood. I'm having troubles myself with parsing its meaning here.

2024-06-18 08:11 UTC, boucadair commented on IAB Workshop.md
> +networks has recently been held [RFC9490]; Another workshop dedicated
```suggestion
networks has recently been held [RFC9490]. Another workshop dedicated
```

2024-06-18 08:11 UTC, boucadair commented on IAB Workshop.md
> +to environment impact of internet application and system has also been held
```suggestion
to environment impact of Internet applications and systems has also been held 
```

2024-06-18 08:11 UTC, boucadair commented on IAB Workshop.md
> +[RFC9547]. These topics are therefore out of scope for this workshop.
```suggestion
[RFC9547]. These topics are, therefore, out of scope for this workshop.
```

2024-06-18 08:11 UTC, boucadair commented on IAB Workshop.md
> +Assuming this trend will continue, this workshop's incentive is
```suggestion
Assuming this trend will continue, this workshop's ambition is
```

2024-06-18 08:11 UTC, boucadair commented on IAB Workshop.md
> +RESTCONF [RFC8040], and most recently CORECONF [I.D-ietf-core-comi].
```suggestion
RESTCONF [RFC8040], and most recently CORECONF [I-D.ietf-core-comi].
```

2024-06-21 18:06 UTC, merged